// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfzkreaylakmvlrbbjci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5memtyZWF5bGFrbXZscmJiamNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2OTQ3NTYsImV4cCI6MjA5MTI3MDc1Nn0.TQSFvKQUdOB0MRHepxfAiaMESrroiWENjheWDIyoVuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});